export const AUTH_ERROR = "AUTH_ERROR";
export const USER_PROFILE_LOADED = "USER_PROFILE_LOADED";
export const LOGIN = "LOGIN";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REGISTER = "REGISTER";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOG_OUT = "LOG_OUT";
export const CLEAR_TODO = "CLEAR_TODO";
export const TODO_INFO_LOADED = "TODO_INFO_LOADED";
export const TODO_UPDATE_ERROR = "TODO_UPDATE_ERROR";
export const TODO_UPDATE_SUCCESS = "TODO_UPDATE_SUCCESS";
export const UPDATE_DETAILS = "UPDATE_DETAILS";

export const DELETE_A_GROUP = "DELETE_A_GROUP";
export const TODO_ADD_ERROR = "TODO_ADD_ERROR";
export const TODO_ADD_SUCCESS = "TODO_ADD_SUCCESS";

export const TODO_GROUP_ADD_SUCCESS = "TODO_GROUP_ADD_SUCCESS";
export const TODO_GROUP_ADD_ERROR = "TODO_GROUP_ADD_ERROR";
export const TODO_GROUP_DELETE_SUCCESS = "TODO_GROUP_DELETE_SUCCESS";
export const TODO_GROUP_DELETE_ERROR = "TODO_GROUP_DELETE_ERROR";

export const TODO_DELETE_SUCCESS = "TODO_DELETE_SUCCESS";
export const TODO_DELETE_ERROR = "TODO_DELETE_ERROR";

export const ADD_MESSAGE = "ADD_MESSAGE";
export const REMOVE_MESSAGE = "REMOVE_MESSAGE";


